### ISSUE TITLE
No regresa bien error conekta

### ISSUE THREAD

**Issue by gerson22** [Curiosity-Education/curiosity-v.1.0#384]
Cuando realizo un pago y no pasa tarjeta no regresa bien el error

**Comment by gerson22** [comment]
El pull request #389  ya arreglo este problema
Ahora regresa un error con los siguientes atributos
status : 105
statusMessage: PAST_DUE
data: suscripton_object
message:"El pago no fue realizado con éxito."

**Comment by rogelioRa** [comment]
Esto esta padre jeje.
